- name: Ethical Hacking website with Docker
  hosts: all
  become: false

  tasks:
    - name: Ensure Bash script is executable
      file:
        path: /home/{{ ansible_user }}/containers/4.compose/hack/ansible.sh
        mode: '0755'
        state: file

    - name: Build & deploy the Ethical Hacking website
      shell: script -q -c "./ansible.sh" /dev/null
      args:
        chdir: /home/{{ ansible_user }}/containers/4.compose/hack
        executable: /bin/bash
      register: result
      environment:
        PATH: "{{ ansible_env.PATH }}"

