- name: Pizza website with Docker
  hosts: all
  become: false

  tasks:
    - name: Ensure Bash script is executable
      file:
        path: /home/{{ ansible_user }}/containers/4.compose/pizza/ansible.sh
        mode: '0755'
        state: file

    - name: Build & Deploy the Pizza website
      shell: ./ansible.sh
      args:
        chdir: /home/{{ ansible_user }}/containers/4.compose/pizza
      environment:
        PATH: "{{ ansible_env.PATH }}"

    - name: Get Pizza website deployment log
      shell: cat pizza.log
      args:
        chdir: /home/{{ ansible_user }}/containers/4.compose/pizza
      register: pizza_log

    - name: Print Pizza website deployment log
      debug:
        msg: "{{ pizza_log.stdout_lines }}"
