- name: Pizza website with Docker
  hosts: all
  become: false

  tasks:
    - name: Ensure Bash script is executable
      file:
        path: /home/{{ ansible_user }}/containers/4.compose/pizza/ansible.sh
        mode: '0755'
        state: file

    - name: Build & Run the Pizza website
      shell: |
        cd /home/{{ ansible_user }}/containers/4.compose/pizza
        ./start-ansible.sh
      args:
        chdir: /home/{{ ansible_user }}/containers/4.compose/pizza
      environment:
        PATH: "{{ ansible_env.PATH }}"
