name: Automated Integrate

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

  plan:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -out=planfile
        working-directory: terraform

      - name: Upload Planfile as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-planfile
          path: terraform/planfile

  test:
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Unit Test
        run: terraform test --test-directory=tests/unit
        working-directory: terraform

      - name: Setup Private Key for Remote Connections
        run: |
          mkdir -p keys
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > keys/b2111933-pair.pem
          chmod 600 keys/b2111933-pair.pem

      - name: Terraform Integration Test
        run: terraform test --test-directory=tests/integration
        working-directory: terraform
