name: Automated Integrate

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_DEFAULT_REGION: "ap-southeast-1"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

  tfvars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Write TFVARS file
        run: |
          mkdir -p terraform
          cat <<EOF > terraform/provision.tfvars
          ${{ vars.NW_TFVARS }}

          ${{ vars.SG_TFVARS }}

          ${{ vars.VM_TFVARS }}
          EOF

      - name: Upload TFVARS file
        uses: actions/upload-artifact@v4
        with:
          name: tfvars
          path: terraform/provision.tfvars

  test:
    runs-on: ubuntu-latest
    needs:  [validate, tfvars]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Unit Test
        run: terraform test --test-directory=tests/unit
        working-directory: terraform

      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('ansible/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python and Ansible dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          python3 -m pip install --upgrade pip
          pip3 install -r ansible/requirements.txt

      - name: Setup Private Key for Remote Connections
        run: |
          mkdir -p keys
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > keys/b2111933-pair.pem
          chmod 600 keys/b2111933-pair.pem

      - name: Download TFVARS
        uses: actions/download-artifact@v4
        with:
          name: tfvars
          path: terraform

      - name: Terraform Integration Test
        run: terraform test -var-file="provision.tfvars"
        working-directory: terraform

  plan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Download TFVARS
        uses: actions/download-artifact@v4
        with:
          name: tfvars
          path: terraform

      - name: Terraform Plan
        run: terraform plan -out=planfile -var-file="provision.tfvars"
        working-directory: terraform

      - name: Upload Planfile as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-planfile
          path: terraform/planfile