name: Manual Update Application

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6

      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('ansible/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python and Ansible dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          python3 -m pip install --upgrade pip
          pip3 install -r ansible/requirements.txt

      - name: Save pip cache
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('ansible/requirements.txt') }}

      - name: Setup Private Key for Remote Connections
        run: |
          mkdir -p keys
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > keys/b2111933-pair.pem
          chmod 600 keys/b2111933-pair.pem

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -out=planfile-update
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -input=false planfile-update
        working-directory: terraform